name: xpool
description: XPool 

publish_to: "none"

version: 2.0.0+79
## Slidy Scripts ##
vars:
  clean: flutter clean
  get: flutter pub get
  runner: flutter pub run build_runner

scripts:
  br_build: $runner build
  br_watch: $clean & $get & $runner watch
  br_build_clean: $clean & $get & $runner build --delete-conflicting-outputs

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_modular: ^5.0.2
  flutter_triple: ^1.2.5
  dio: ^4.0.1
  dartz: ^0.10.0-nullsafety.1
  asuka: ^2.0.0-nullsafety.2
  flutter_svg: ^1.0.3
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  mobx_triple: ^1.1.3+1
  brasil_fields: ^1.1.2
  animated_bottom_navigation_bar: ^0.3.2
  carousel_slider: ^4.0.0-nullsafety.0
  dropdown_search: ^4.0.1
  font_awesome_flutter: ^10.1.0
  mocktail: ^0.3.0
  transparent_image: ^2.0.0
  connectivity: ^3.0.6
  change_app_package_name: ^1.0.0
  onesignal_flutter: ^3.2.0
  modal_bottom_sheet: ^2.0.1
  cached_network_image: ^3.2.1
  flutter_launcher_icons: ^0.9.2
  url_launcher: ^6.0.11
  shimmer: ^2.0.0
  google_places_flutter: 
    git:
      url: https://github.com/rdosolucoes/Google-AutoComplete-TextField-Flutter.git
  image_picker: ^0.8.4+4
  http_parser: ^4.0.0
  azblob: ^2.0.0
  mime: ^1.0.1
  search_cep: ^4.0.0
  intl: ^0.17.0
  flutter_localizations: 
    sdk: flutter
  pin_code_fields: ^7.3.0
  flutter_slidable: ^1.2.1
  brazilian_banks: ^0.5.1
  cpf_cnpj_validator: ^2.0.0
  credit_card_validator: ^2.0.1
  responsive_framework: ^0.2.0
  confirm_dialog: ^1.0.1
  share_plus: ^4.0.10
  encrypt: ^5.0.1
  infinite_scroll_pagination: ^3.2.0


  
  

dev_dependencies:
  analyzer: ^4.1.0
  build_runner: ^2.1.2
  effective_dart: ^1.3.1
  ##flutter_test:
  ##  sdk: flutter
  hive_generator: ^1.1.0
  http_mock_adapter: ^0.3.2
  ##mockito: ^5.0.5
  ##triple_test: ^0.0.5
  package_info: ^2.0.0
  

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/creditCards/

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik/Rubik-Italic-VariableFont_wght.ttf
          style: italic
        - asset: assets/fonts/Rubik/Rubik-VariableFont_wght.ttf
        - asset: assets/fonts/Rubik/static/Rubik-Bold.ttf
          weight: 700

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/app_icon.png"
